# Generated by Django 6.0.7 on 2026-07-08 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=120)),
                ('state', models.CharField(max_length=80)),
                ('price', models.DecimalField(decimal_places=5, max_digits=6)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('geocoded', models.BooleanField(default=False)),
                ('source_row', models.IntegerField(default=0)),
            ],
            options={
                'indexes': [models.Index(fields=['state', 'city'], name='route_optim_state_ec4fa5_idx'), models.Index(fields=['price'], name='route_optim_price_7774e0_idx')],
            },
        ),
    ]
